feat: Added passOnStoreError to skip rate limitter if the store is not available
express-rate-limit/express-rate-limit pull request #447
Opened 2024-03-20 11:36 UTC by Gp2mv3

This PR adds the parameter passOnStoreError to allow requests if the store is not available.
For instance, if using Redis and the Redis server disconnects, the request will still pass.

This feature can be important for HA issues.

2024-03-20 13:47 UTC, nfriedly requested changes
Good idea, thanks!


A few thoughts:

1. There's a lot of "stuff" inside the try/catch besides the store.increment() call, so I think it should either be renamed to `passOnError` or else the try/catch should be more narrowly scoped to only the increment call.
    * I'm leaning towards the rename option, but I could see a good argument for the other side.
2. If we go with the rename option, it should probably hook into the existing `handleAsyncErrors`: https://github.com/express-rate-limit/express-rate-limit/blob/e3e3ca9f672fa5a0708fa62e5c1358c2cbdcecc3/source/lib.ts#L284
3. Regardless, I think it should log the error, not just silently allow the request.

What do you think @gamemaker1 ?

2024-03-20 13:48 UTC, nfriedly commented
Oh, and this PR closes https://github.com/express-rate-limit/rate-limit-redis/pull/193

2024-03-21 15:52 UTC, gamemaker1 commented
Hi @gp2mv3, thanks for making this PR!

> 1. There's a lot of "stuff" inside the try/catch besides the store.increment() call, so I think it should either be renamed to `passOnError` or else the try/catch should be more narrowly scoped to only the increment call.

I think we should keep it `passOnStoreError`, and scope it to the increment call as you said.

The `passOnStoreError` option has already been requested in `rate-limit-redis`, and I think it'd be better if we just provide it as part of `express-rate-limit`.

> 3. Regardless, I think it should log the error, not just silently allow the request.

I agree, we should make this addition to `handleAsyncErrors` regardless of the `passOnStoreError` option.

2024-03-21 17:21 UTC, gamemaker1 commented
By point 3, we mean logging the error before calling `next()`.

Also logging the error in `handleAsyncError` can be done in a separate pr.

2024-03-21 17:36 UTC, nfriedly commented
> Also logging the error in `handleAsyncError` can be done in a separate pr.

`handleAsyncError` currently passes the error onto express.js to handle however it's configured to (show an error page by default), so no need to change it unless we add an option that ignores those errors.

https://github.com/express-rate-limit/express-rate-limit/blob/e3e3ca9f672fa5a0708fa62e5c1358c2cbdcecc3/source/lib.ts#L291

2024-03-21 17:42 UTC, nfriedly commented on source/lib.ts
> +					next()
```suggestion
					console.error('express-rate-limit: error from store, allowing request without rate-limiting.', error)
					next()
```

This is what I meant by point 3.

2024-03-21 17:42 UTC, nfriedly commented on test/library/middleware-test.ts
> +	})
I forgot to say it last time, but thank you for adding these tests!

2024-07-17 22:36 UTC, nfriedly approved these changes

2024-07-17 22:58 UTC, closed without merging

2024-07-17 23:01 UTC, nfriedly commented
Oops, I wasn't trying to close this. I checked it out locally to fix the lint errors, and then I also rebased it and changed the `throw` to a `next(error)`, although I want to test that a bit more. 

Also, we need to add documentation for this

2024-07-17 23:01 UTC, nfriedly commented
Re-opening